# backend/app/schemas/job_schema.py

from pydantic import BaseModel, Field
from datetime import datetime

class JobRequest(BaseModel):
    processing_code: str = Field(..., description="Unique code generated by front")

class JobResponse(BaseModel):
    job_id: str
    processing_code: str
    created_at: datetime
